#!/bin/sh

# A sample pre-connect check
#
# Warms DNS before connecting to hosts in parallel
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLE (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME

ssh root@$KAMAL_HOSTS 'mkdir -p /test'
ssh root@$KAMAL_HOSTS 'echo "Hello, World!" > /test/hello.txt'
